### ISSUE TITLE
entity invisible with entityculling 

### ISSUE THREAD

**Issue by ralseilii** [Asek3/sodium-1.12#10]
### Bug Description

When sodium installed alongside EntityCulling-1.12.2-4.2.5, it causes all entities to become invisible. In reality, the latest version of EntityCulling is 6.4.2, but Cleanroom does not support its dependency renderlib. The latest version of EntityCulling that does not rely on renderlib is 4.2.5.

### Reproduction Steps

download EntityCulling-1.12.2-4.2.5 with sodium, and enter game, spawn a creature

### Log File

no log

**Comment by Asek3** [comment]
Vintagium is not and probably will never be compatbile with EntityCulling since it doing the same as Vintagium
