### ISSUE TITLE
Issues with Greenery (Water appears invisible with some of its plant types)

### ISSUE THREAD

**Issue by aking4125** [Asek3/sodium-1.12#15]
### Bug Description

Hello, Upon using this and [Greenery](https://github.com/juraj-hrivnak/Greenery). There seems to be a visual problem with the water plants. The water doesn't render (as it's kinda water logged sorta) but still functions as water (You can swim in it)

![2024-02-10_07 15 27](https://github.com/Asek3/sodium-1.12/assets/11141831/675f1743-0001-4d03-b051-8f746deb4605)

![2024-02-10_07 15 36](https://github.com/Asek3/sodium-1.12/assets/11141831/20355d7c-470e-472f-bd2f-ba4a17d33102)

### Reproduction Steps

It is a modpack but I guess install this and [Greenery](https://github.com/juraj-hrivnak/Greenery) and watch for the above screen shots?

### Log File

[debug.zip](https://github.com/Asek3/sodium-1.12/files/14229221/debug.zip)

**Comment by embeddedt** [comment]
This looks like the same issue as https://github.com/Asek3/sodium-1.12/issues/6; we don't have Fluidlogged API integration yet.
