### ISSUE TITLE
I literally can't load up Vintagium!

### ISSUE THREAD

**Issue by Parrottitan** [Asek3/sodium-1.12#19]
### Bug Description

So, I have no other mods loaded besides  Vintagium (I do have java 21 CleanroomLoader too) and I cannot load up the game, every single time I get an error when I use prism launcher. (same with multimc)

### Reproduction Steps

First go to prism launcher and install java 21 CleanroomLoader and then second get minecraft 1.12.2 and get the forge version 14.23.5.2859, and then you install Vintagium, and now what you do is run minecraft.

### Log File

https://mclo.gs/3MyrDf2

**Comment by japanesetelevision** [comment]
MixinBooter is included in CleanroomLoader...

**Comment by japanesetelevision** [comment]
Wait are you not using CleanroomLoader?

**Comment by Parrottitan** [comment]
> Wait are you not using CleanroomLoader?

I am using cleanroomloader

**Comment by Parrottitan** [comment]
https://mclo.gs/3MyrDf2 here is the log without using mixinbooter mod.

**Comment by kappa-maintainer** [comment]
That's just trying to run a regular Forge on Java 21, I don't see any sign of Cleanroom installed

**Comment by Asek3** [comment]
Unrelated to Vintagium
