### ISSUE TITLE
Crashes with GTCEu

### ISSUE THREAD

**Issue by Meatwo310** [Asek3/sodium-1.12#21]
### Bug Description

The game crashes when loading worlds if using Vintagium and GTCEu (+ other mods) at the same time in a Cleanroom Loader environment using Prism Launcher.

### Reproduction Steps

- Set up Prism Launcher and Java 21.
- After importing [CleanroomMMC](https://github.com/CleanroomMC/CleanroomMMC) with Prism, change the Java to be used to Java 21 (e.g. `/usr/lib/jvm/java-21-openjdk-amd64/bin/java`) and disable compatibility checks.
- Add the following mods to your instance:
  - Vintagium (0.1)
  - [GregTech CE: Unofficial](https://github.com/GregTechCEu/GregTech) (2.8.7-beta)
    - [CodeChickenLib](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8) (3.2.3.358)
  - [Fugue](https://github.com/CleanroomMC/Fugue) (0.5.4) [Required to run GTCEu in the Cleanroom Loader enviroment]
- Launch the instance, create and load a new world.
- The game crashes and outputs `java.util.concurrent.ExecutionException: java.lang.NullPointerException: No render pass exists for layer: Bloom` and lots of errors.

### Log File

[latest.log](https://github.com/Asek3/sodium-1.12/files/14354363/latest.log)

**Comment by Meatwo310** [comment]
Related: #17

**Comment by Asek3** [comment]
Look at #17
