### ISSUE TITLE
This Is A Virus Don't Download This Mod

### ISSUE THREAD

**Issue by Danmccool** [Asek3/sodium-1.12#26]
### Bug Description

The Title Says It All

### Reproduction Steps

Try To Download This Mod Then You Will See That This Is A Virus

### Log File

no log

**Comment by medcorn** [comment]
Also got a trojan warning

**Comment by Danmccool** [comment]
Hope They Can Try To Fix This Or Tell Us Why They Put A Virus In This Mod

**Comment by Asek3** [comment]
Don't spread misinformation here. All code is open for viewing and available for download via GitHub Actions

If you downloaded a mod from a third-party site and came across a virus, this is solely your problem

**Comment by Danmccool** [comment]
I Downloaded it From The Actions Tab

**Comment by quentin452** [comment]
maked a virustotal scan and no virus :D : https://www.virustotal.com/gui/file-analysis/NWI1Y2NiNDM2MzM3NzUwNzMxMjBlMDQ0YTE5N2Q2ZTI6MTcwOTc2ODM1NA==

**Comment by Asek3** [comment]
> I Downloaded it From The Actions Tab
> 
> 

All code is available for viewing, GitHub Actions are collected from the code posted in the repository. Again, don't spread misinformation.

**Comment by Danmccool** [comment]
![image_2024-03-06_185841551](https://github.com/Asek3/sodium-1.12/assets/121473014/6867b544-284a-45c4-8817-fa6806b4655c) Look At This

**Comment by kappa-maintainer** [comment]
Just regular Chrome being stupid.
Please trust Virus Total or any antivirus installed.

**Comment by Roadhog360** [comment]
I'd say you should listen to:
- Windows Defender (modern)
- ESET
- Malwarebytes
- Virustotal

Anything else is shoddy at best. Don't listen to shitty antivirus software that comes with your browser, it is rarely accurate.
