### ISSUE TITLE
windows defender and chrome flagging file as containing a trojan, this does not happen on any builds prior to the latest from 2 days ago

### ISSUE THREAD

**Issue by Ajw2003** [Asek3/sodium-1.12#27]
### Bug Description

microsoft defender flags the newest build artifact as a trojan when attempting to download on either edge or chrome 
![Screenshot 2024-03-07 140429](https://github.com/Asek3/sodium-1.12/assets/79066376/fef2369c-b285-4ea6-99eb-5cc673b04e18)

this does not occur on previous build artifacts, thus something has to have changed in the code to cause this, even if it is a false positive.

### Reproduction Steps

download the most recent build artifact directly from this git hub, use either edge or chrome, gets flagged as a virus by both and as a trojan by defender.

again this only occurs with the most recent build from 2 days ago, the previous builds I've downloaded do not have this issue

### Log File

n/a

**Comment by Kasualix** [comment]
> this does not occur on previous build artifacts, thus something has to have changed in the code to cause this, even if it is a false positive.

Actually it is Windows defender that changes their code and causes this. [Rage Mod](https://legacy.curseforge.com/minecraft/mc-mods/rage-mod) & [ModernFix](https://legacy.curseforge.com/minecraft/mc-mods/modernfix) and this mod all have this issue (reported by different guys). And I'm sure it's definitely not limited to those three mods either
