### ISSUE TITLE
Vintagium rendering problem with HBM NuclearTech and Openblocks blocks and tiles

### ISSUE THREAD

**Issue by BloxMaster3** [Asek3/sodium-1.12#29]
### Bug Description

game crashes when HBM or Openblocks blocks or tiles are in the world and rendered

### Reproduction Steps

have HBM and/or Openblocks installed along with Vintagium and place down a block or tile from those mods (RBMK from HBM or Block Placer from OpenBlocks worked for me) and it should crash

### Log File

I switched back to Optifine after having this problem to see if it's Vintagium causing it and it works fine now so I don't have a correct log but here are the crash reports (yes there are two but it gave me two when it crashed)
[crash-2024-03-13_18.22.43-server.txt](https://github.com/Asek3/sodium-1.12/files/14594732/crash-2024-03-13_18.22.43-server.txt)
[crash-2024-03-13_18.22.40-client.txt](https://github.com/Asek3/sodium-1.12/files/14594733/crash-2024-03-13_18.22.40-client.txt)

**Comment by NostalgicLorikeet** [comment]
I have a pack with Vintagium and Openblocks and haven't had this happen to me, so probably fixed in latest version?

**Comment by BloxMaster3** [comment]
> I have a pack with Vintagium and Openblocks and haven't had this happen to me, so probably fixed in latest version?

maybe its only an hbm problem?

**Comment by BloxMaster3** [comment]
Yeah, I don't know, my PC is currently down so I can't test it

**Comment by BloxMaster3** [comment]
> > > I have a pack with Vintagium and Openblocks and haven't had this happen to me, so probably fixed in latest version?
> > 
> > 
> > maybe its only an hbm problem?
> 
> Works fine with the latest release of HBM Extended Edition (1.12 fork) and with the latest(0.4.2) vintagium, no problems at all

Yeah, I don't know, my PC is currently down so I can't test it

**Comment by BloxMaster3** [comment]
just tested it with only mixinbooter and vintagium and it still wont load even a new world so I'm creating a new issue and closing this one
