### ISSUE TITLE
Crash On latest Cleanroom

### ISSUE THREAD

**Issue by Steven11q** [Asek3/sodium-1.12#33]
### Bug Description

Probably redundant and will be fixed when updated, but currently this mod doesen't function with latest (granted, non-stable) release(3034), IE: the release that works with fugue (3034).  This mod seems to work perfectly fine on 3029 however. 

### Reproduction Steps

Install fugue, vintagium and required version of cleanroom
load game, 
enter world, and crash

### Log File

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9a1b1da1a, pid=29508, tid=12936
#
# JRE version: Java(TM) SE Runtime Environment (21.0.2+13) (build 21.0.2+13-LTS-58)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.2+13-LTS-58, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0xbada1a]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=UTF-8 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10096m -Duser.language=en -Djava.library.path=C:/Users/HomeAdmin/AppData/Roaming/PrismLauncher/instances/cleanroom test/natives org.prismlauncher.EntryPoint

Host: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1566)
Time: Wed Mar 27 22:10:22 2024 Eastern Daylight Time elapsed time: 77.321677 seconds (0d 0h 1m 17s)

---------------  T H R E A D  ---------------

Current thread (0x00000185ec57d580):  JavaThread "Client thread"        [_thread_in_native, id=12936, stack(0x0000004f10c00000,0x0000004f10d00000) (1024K)]

Stack: [0x0000004f10c00000,0x0000004f10d00000],  sp=0x0000004f10cfd4c8,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [nvoglv64.dll+0xbada1a]

(cut off the rest for sake of brevity )

**Comment by kappa-maintainer** [comment]
Can't reproduce under Linux, maybe you should try a different jvm

**Comment by Asek3** [comment]
Can't be related to Vintagium, something wrong with your JVM or native files

**Comment by Steven11q** [comment]
Updating my graphics driver fixed the issue, Thank you!
