### ISSUE TITLE
Faild too boot in Arch linux

### ISSUE THREAD

**Issue by s0u7a** [Asek3/sodium-1.12#35]
### Bug Description

Log:https://mclo.gs/an6tdC3 I downloaded the latest version of Vintagium and cleanroomlauncher and am running it with Java 21 (extra/jre21-openjdk) Without Vintagium it works.

### Reproduction Steps

Install ArchLinux(i3wm)
sudo pacman -S prismlauncher jre21-openjdk
launch prismlauncher 
add cleanroom launcher
add sodium 1.12
change java settings and disable compatibility check
launch
failed

### Log File

https://mclo.gs/an6tdC3

**Comment by s0u7a** [comment]
I searched for the same problem.

**Comment by s0u7a** [comment]
Crashes when all Minecraft has finished loading

**Comment by kappa-maintainer** [comment]
Try latest Cleanroom and regular Forge
And please report any problem on Cleanroom to CleanroomMC first

**Comment by s0u7a** [comment]
I don't think this is a cleanroomlauncher problem because it works with cleanroomlauncher alone

**Comment by s0u7a** [comment]
latest forge+latest MixinBooter+latest vintagiumで動作しました。

**Comment by kappa-maintainer** [comment]
> I don't think this is a cleanroomlauncher problem because it works with cleanroomlauncher alone

I broke ModContainer loading in recent commit and just fixed today
This problem won't happen without mods, cause it was mod container
You need to run on regular Forge to check if it is a mod problem or Cleanroom problem

**Comment by s0u7a** [comment]
It worked with the latest forge+the latest mixinbooter+the latest vintagium!

**Comment by kappa-maintainer** [comment]
> I don't think this is a cleanroomlauncher problem because it works with cleanroomlauncher alone

I broke ModContainer loading in recent commit and just fixed today
This problem won't happen without mods, cause it was mod container
You need to run on regular Forge to check if it is a mod problem or Cleanroom problem

**Comment by kappa-maintainer** [comment]
Now close this and open issue in Cleanroom

**Comment by s0u7a** [comment]
OK
