### ISSUE TITLE
A way for the mod to handle GTCEu bloom layers without crashing?

### ISSUE THREAD

**Issue by NostalgicLorikeet** [Asek3/sodium-1.12#41]
### Request Description

Is there any possible way to fix the issue with GTCEu blocks' rendering as possibly a temporary fix before it's fixed on their side? I haven't had any luck with vintagium-mixins.properties in figuring out what the exact issue is. There's a lot of features in Vintagium I wish I could also have with GT at the same time (ex. Vintagium seems to be the only mod I can find that mostly eliminates mass block particle lags).

Looking through crash logs it says `No render pass exists for layer: Bloom` which appears to be relevant to this class: https://github.com/Asek3/sodium-1.12/blob/12.x/forge/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/passes/BlockRenderPassManager.java

**Comment by NostalgicLorikeet** [comment]
Reported this to GTCEu dev's here: https://github.com/GregTechCEu/GregTech/issues/2462, as you've said before I'm not sure if there's any way for this to be fixed on Vintagium's end

**Comment by NostalgicLorikeet** [comment]
This was fixed in the `ht-vintagium` branch, btw.

**Comment by Asek3** [comment]
Update GTCEu
