### ISSUE TITLE
Moving Elevators mod elevator entity is invisible

### ISSUE THREAD

**Issue by Ijustplaymc** [Asek3/sodium-1.12#44]
### Bug Description

The elevator entity (When moving) is invisible with this mod enabled.
Mod is Moving elevators, which adds elevators that move up and down using an entity
https://www.curseforge.com/minecraft/mc-mods/moving-elevators

Modlist is : Vintagium, VintagFix, Mousetweaks, Moving elevators and its dependencies

Screenshots :

Elevator when at bottom of floor and still
![ElevatorStandby](https://github.com/Asek3/sodium-1.12/assets/98615903/f5a8d7a0-512d-4a8a-8fdd-a44407258a04)
Elevator when moving and invisible (Entity hitboxs enabled)
![InvisibleElevator](https://github.com/Asek3/sodium-1.12/assets/98615903/9b4f14d8-12b0-4dcf-9a52-a61578c42d4a)
Same thing but player is on elevator
![InvisibleElevatorPlayerView](https://github.com/Asek3/sodium-1.12/assets/98615903/5a6e27f5-8885-499d-bd97-fbb8d85390a7)

No odd issues in log file
Does not occur when Vintagium is disabled

### Reproduction Steps

Install Moving Elevators and its dependencies
Install this mod
Create a valid elevator setup (2 floors, controllers, platform)
Attempt to use the elevator only to see when its moving (Ie, elevator entity) it is invisible

### Log File

[latest.log](https://github.com/Asek3/sodium-1.12/files/15284203/latest.log)

**Comment by Asek3** [comment]
It turns out that MovingElevators uses Mixins to inject into chunk render code. Please write a report to the developer of this mod. They already have integration with Sodium on newer versions, I think it won't be a problem for 1.12 as well
