### ISSUE TITLE
Can't download latest build

### ISSUE THREAD

**Issue by gohellp** [Asek3/sodium-1.12#48]
Build triggered by 29dc4a8 have artifact marked as expired. Can you run build?

**Comment by Asek3** [comment]
Pushed PR https://github.com/Asek3/sodium-1.12/actions/runs/9866213559

**Comment by sillyOSM0** [comment]
same shit again, latest run https://github.com/Asek3/sodium-1.12/actions/runs/11309063708 expired, can you just upload file to google drive or something?
